# -*- coding: utf-8 -*-
"""RegBeta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNCrIo6rvHQRRROcsLQmEegHDhgquXcn
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("feature_matrix_no_intercept.csv")
y = np.array([
    450, 300, 400, 180, 420, 350, 170, 500, 360, 160,
    380, 460, 320, 175, 490, 290, 240, 480, 310, 150
])
X = df.values
X = df.drop(columns=["Rural"]).values
X = np.hstack((np.ones((X.shape[0], 1)), X))

XtX = X.T @ X
XtX_inv = np.linalg.inv(XtX)
XtY = X.T @ y
beta = XtX_inv @ XtY

# Step 7: Output the coefficients
print("Regression coefficients (Beta):")
for i, b in enumerate(beta):
    print(f"Beta{i}: {b:.4f}")